print("+------------------------------------------------+")
print("|    |                                           |")
print("|   -|          Lander, Andrew                   |")
print("|  --|          Tribute Liabilities Associate    |")
print("| ---|          Parasail Capital                 |")
print("| ---------                                      |")
print("|  -------      4 Hunger Plaza                   |")
print("|               STE 1400                         |")
print("|               District 12, Panem 00012         |")
print("|                                                |")
print("| Work: (406)220-0734 @: andrew@parasail.com     |")
print("+------------------------------------------------+")